In [ ]:
import numpy as np
from numpy import empty
import random

## Randomly generate individual set of parameters within specified values

In [ ]:
def generate_individual():
    
    L = random.uniform(5, 15)
    P = random.uniform(20e-3, 200e-3)
    W = random.choice([980, 1480])
    
    individual = [L, P, W]
    
    return individual

## Generate initial population

In [ ]:
def generate_initial_population(size):
    
    pop = np.zeros([size, 3])
    
    for i in range(size):
        pop[i] = generate_individual()
        
    return pop

population = generate_population(100)

range(len(population))

## Determine fitness levels of the generation

In [ ]:
def fitness_calc(population):
    
    solution = np.zeros([range(len(population))])
    
    for i in range(len(population)):
    
        solution[i] = ((individual[i][0]*individual[i][1]*individual[i][2])/3)

    fitness_array = np.zeros([range(len(solution))])
    
    for i in range(len(solution)):
    
        fitness_array[i] = solution[i] - 485.1409107132838

    return fitness_array

## Select new mating pool based on fittest genes

In [ ]:
def select_mating_pool(population, fitness, num_parents):
    
    parents = np.zeros([num_parents, len(population[1])])
    
    for parent_num in range(num_parents):
        
        max_fitness_i = numpy.where(fitness = numpy.min(abs(fitness)))
        
        max_fitness_i = max_fitness_i[0][0]
        
        parents[parent_num, :] = population[max_fitness_i, :]
        
        fitness[max_fitness_i] = 999999999
        
    return parents

## Mix genes to produce offspring

In [ ]:
def crossover(parents, offspring_size):
    
    offspring = np.zeros(offspring_size)
                         
    crossover_point = np.uint8(len(offspring_size[1])/2)
                         
    for i in range(len(offspring_size)):
                         
        parent1_i = parents[i]
        parent2_i = parents[i+1]
                         
        offspring[i, 0:crossover_point] = parents[parent1_i, 0:crossover_point]
                         
        offspring[i, crossover_point:] = parents[parent2_i, crossover_point:]
                         
    return offspring

## Mutate 1 gene (in this case fibre length)

In [ ]:
def mutation(offspring_crossover):
    
    for i in range(offspring_crossover):
        
    random_value = np.random.uniform(-3, 3)
    
    offspring_crossover[i, 0] = offspring_crossover[i, 0] + random_value
    
    return offspring_crossover

## Wrapper function 

In [ ]:
def ga_wrapper(num_generations, num_parents_mating, pop_size):
    
    population = generate_initial_population(pop_size) 
    
    generations = np.zeros(range(len(num_generations))
    
    for generation in range (num_generations):
        
        fitness_array = fitness_calc(population)
        
        parents = select_mating_pool(new_poulation, fitness_array, num_parents_mating)
        
        offspring_crossover = crossover(parents, offspring_size=(len(pop_size)-len(parents))
                                        
        offspring_mutation = mutation(offspring_crossover)                    
                                        
        generations[generation] = zip(population, fitness_array)
                                        
        population[0:len(parents), :] = parents
        population[len(parents):, :] = offspring_mutation
                                        
    return generations

In [ ]:
def print_results(generations)

    for i in range(len(generations)):
        print("Generation {}".format(i))
        print()
        print("Parameters:")
        print()
        print(generations[i].population)
        print("Fitness Values:")
        print()
        print(generations[i].fitness_array)
        print()
        print("Best result: {}".format(min(abs(generations[i].fitness_array))))

# Ignore everything below

In [78]:
solution = np.zeros([100, 1])

for i in range(len(population)):
    solution[i] = ((population[i][0]*population[i][1]*population[i][2])/3)
    
solution

array([[1332.46626224],
       [ 973.63287382],
       [  79.36291052],
       [ 390.99796817],
       [1140.55085629],
       [ 320.68851849],
       [ 306.44094028],
       [ 638.76865307],
       [ 151.69384099],
       [ 290.57775422],
       [ 132.444243  ],
       [ 330.28261131],
       [ 438.99325034],
       [ 446.7887986 ],
       [ 675.2130767 ],
       [ 484.50327072],
       [ 384.36988243],
       [ 422.58849295],
       [ 787.86931186],
       [ 596.76710286],
       [ 120.0994219 ],
       [ 132.14826313],
       [1229.70210073],
       [ 748.67401561],
       [ 331.21427149],
       [ 247.36161305],
       [ 418.05680648],
       [ 811.18462651],
       [ 336.94947546],
       [ 669.42895448],
       [ 170.63452128],
       [ 944.46167731],
       [ 355.46424687],
       [ 483.61744084],
       [1125.86333891],
       [ 101.64283309],
       [ 271.87839655],
       [ 428.54073696],
       [1023.34843653],
       [ 717.92611794],
       [  98.41624957],
       [ 833.392

In [73]:
np.mean(solution)

485.1409107132838

In [82]:
a = fitness(population)
min(abs(a))

array([0.63764])

In [89]:
parents = np.empty((10, 3))
parents

array([[1.05475334e-311, 9.58487353e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [3.79823469e+175, 1.16391660e+165, 1.79584374e-052],
       [4.08594369e+179, 5.01163111e+217, 5.49419094e-143],
       [9.80058441e+252, 1.30304358e-142, 2.14027814e+161],
       [5.04621383e+180, 4.50618615e-144, 7.79952704e-143],
       [6.01352666e-067, 2.62967465e+179, 8.70264083e-071],
       [3.79100468e+179, 1.41529403e+161, 9.16651763e-072],
       [4.31217112e+097, 1.14482968e-071, 3.08395576e+126],
       [9.30350598e+199, 3.67152475e-062, 1.58268989e-319]])

In [92]:
len(population[1])

3

In [104]:
parents = (1, 10, 1)

# parent_num = 10
# parents[parent_num, :]

for i in range(len(parents)):
    print(i%parents)

TypeError: unsupported operand type(s) for %: 'int' and 'tuple'

In [103]:
offspring_size = 4

offspring = np.zeros(offspring_size)

offspring

array([0., 0., 0., 0.])

In [113]:
generations = np.arange(2, 11, 1)
generations

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
for i in range(len(generations)):
    print("Generation {}".format(i+1))
    print()
    print('i')

Generation 1

i
Generation 2

i
Generation 3

i
Generation 4

i
Generation 5

i
Generation 6

i
Generation 7

i
Generation 8

i
Generation 9

i
